apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: flask-app-in
  namespace: student-38
spec:
  rules:
  - host: arzongina.uz
    http:
      paths:
      - backend:
          service:
            name: check-ingress
            port:
              number: 80
        path: /
        pathType: Exact
status:
  loadBalancer: {}
